version: "2.4"

services:
  monorepo:
    image: monorepo-template-app:0.0.1
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_CANONICAL_URL=http://localhost:3000
